- type: job
  parent: CMJobBase
  id: AU14JobCivilianCMBDeputy
  name: au14-job-name-civiliancmbdeputy
  description: au14-job-description-civiliancmbdeputy
  setPreference: true
  playTimeTracker: AU14JobCivilianCMBDeputy
  ranks:
    AU14RankCMBSrDeputy:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianCMBDeputy
      time: 2400 # 20 hours
    RMCRankCMBDeputy:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianCMBDeputy
      time: 240 # 4 hours
    AU14RankCMBProbDeputy: []
  startingGear: AU14GearCivilianCMBDeputy
  icon: "RMCJobIconBureauDeputy"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - aucmb
  - Colonist
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillEndurance: 2
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillIntel: 1
        RMCSkillMedical: 1
        RMCSkillMeleeWeapons: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillVehicles: 1
    - type: JobPrefix
      prefix: au14-job-prefix-cmbdeputy
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearCivilianCMBDeputy
  equipment:
    head: RMCHeadCapBureau
    jumpsuit: AU14CMBUniform
    belt: CMBeltSecurityMarshalFilled
    shoes: RMCBootsPMCFilled
    id: AU14IDCardColonyCMBDeputy
    ears: AU14CMBHeadset
    outerClothing: AU14CMBDeputyWindbreaker

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianCMBDeputy
  name: Spawn Point Civilian CMB Deputy
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianCMBDeputy
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianCMBDeputy
  isHumanoid: true
