- type: job
  parent: CMJobBase
  id: AU14JobCivilianNurse
  name: au14-job-name-civiliannurse
  description: au14-job-description-civiliannurse
  setPreference: true
  playTimeTracker: AU14JobCivilianNurse
  ranks:
    RMCRankCivilianNurse: []
  startingGear: AU14GearCivilianNurse
  icon: "CMJobIconEmpty"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - Colonist
  - aumed
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillDomestics: 1
        RMCSkillMedical: 2
        RMCSkillSurgery: 1
        RMCSkillFirearms: 1
    - type: JobPrefix
      prefix: au14-job-prefix-nurse
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearCivilianNurse
  equipment:
    id: AU14IDCardColonyNurse
    ears: CMHeadsetColony
    jumpsuit: RMCScrubsLightBlue
    shoes: RMCShoesBlack

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianNurse
  name: Spawn Point Civilian Nurse
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianNurse
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianNurse
  isHumanoid: true
