- type: job
  parent: CMJobBase
  id: AU14JobCivilianUSASFRecruiter
  name: au14-job-name-usasfrecruiter
  description: au14-job-description-usasfrecruiter
  setPreference: true
  playTimeTracker: AU14JobCivilianUSASFRecruiter
  ranks:
    AU14RankUSASFTechnicalSergeant: []
  startingGear: AU14GearCivilianUSASFRecruiter
  icon: "AU14JobIconRFN"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - Colonist
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 1
        RMCSkillEndurance: 1
        RMCSkillVehicles: 1
        RMCSkillPowerLoader: 1
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillJtac: 3
    - type: JobPrefix
      prefix: au14-job-prefix-usasfrecruiter
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearCivilianUSASFRecruiter
  equipment:
    jumpsuit: AU14UASFFatigues
    shoes: RMCBootsCorporate
    id: AU14IDCardColonyUSASFRecruiter
    ears: CMHeadsetColony
    head: AU14USASFCap

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianUSASFRecruiter
  name: Spawn Point USASF Recruiter LV624 SPECIFIC
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianUSASFRecruiter
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianUSASFRecruiter
  isHumanoid: true
