# TODO Recreational
# TODO Miscellaneous

# Auxiliary Support
- type: roleLoadout
  id: JobCMAuxiliarySupportOfficer
  points: 7
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMDropshipCrewChief
  points: 7
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMPilotDropship
  points: 7
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMPilotGunship
  points: 7
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMIntelOfficer
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

# Command
- type: roleLoadout
  id: JobCMCommandingOfficer
  points: 7
  groups:
  - CommandingOfficerIDRMC
  - MarineLeatherBackpack
  - CommandingOfficerRoleSpecificRMC
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMExecutiveOfficer
  points: 7
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMStaffOfficer
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

# Engineering
- type: roleLoadout
  id: JobCMChiefEngineer
  points: 7
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMMaintTech
  points: 7
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMOrdnanceTech
  points: 7
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

# Squad Roles
- type: roleLoadout
  id: JobCMCombatTech
  points: 7
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMFireteamLeader
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMHospitalCorpsman
  points: 7
  groups:
  - MarineMedicBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMRifleman
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMSmartGunOperator
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMSquadLeader
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMWeaponsSpecialist
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

# Medical
- type: roleLoadout
  id: JobCMCMO
  points: 7
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMDoctor
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMNurse
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMResearcher
  points: 7
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

# Military Police
- type: roleLoadout
  id: JobCMChiefMP
  points: 7
  groups:
  - MarineSecurityBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMMilitaryPolice
  points: 7
  groups:
  - MarineSecurityBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMMilitaryWarden
  points: 7
  groups:
  - MarineSecurityBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

# Other
- type: roleLoadout
  id: JobCMCorrespondent
  points: 7
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMLiaison
  points: 7
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMMessTech
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMSeniorEnlistedAdvisor
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobRMCJobSynthetic
  points: 7
  groups:
  - SynthBackpackRMC
  - SynthHeadwearRMC
  - SynthGlassesRMC
  - SynthMasksRMC
  - HelmetGarbsRMC
  - SynthUniformRMC
  - SynthSuitsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - RMCLoadoutGroupPins

# Requsitions
- type: roleLoadout
  id: JobCMCargoTech
  points: 7
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMQuartermaster
  points: 7
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: AU14JobCivilianColonist
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianFoodServiceWorker
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianWasteManagementSpecialist
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianJournalist
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianColonyAdministrator
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianFreightSystemsSpecialist
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianEngineer
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianForeman
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianCorporateLiaison
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianPhysician
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianNurse
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianEthicsAndWellnessAdvisor
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianEmergencyResponseOfficer
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianCMBDeputy
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianCMBMarshal
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCLFGuerilla
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCLFPhysician
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCLFMachineGunner
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCLFCellLeader
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianEcologist
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianUSASFRecruiter
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobCivilianColonySynthetic
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobGOVFORPlatCo
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobGOVFORPlatOp
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobGOVFORDSPilot
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobGOVFORDCC
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobGOVFORSectionSergeant
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobGOVFORSquadSergeant
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobGOVFORSquadRifleman
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobGOVFORSquadAutomaticRifleman
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobGOVFORPlatoonCorpsman
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC

- type: roleLoadout
  id: AU14JobGOVFORRadioTelephoneOoperator
  points: 7
  groups:
  - PaperworkRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC