- type: job
  parent: CMJobBase
  id: CMExecutiveOfficer
  name: cm-job-name-platoon-commander
  description: cm-job-description-platoon-commander
  setPreference: true
  playTimeTracker: CMJobExecutiveOfficer
  ranks:
    RMCRankFirstLT: []
  weight: 5
  startingGear: CMGearExecutiveOfficer
  icon: "CMJobIconExecutiveOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-coyco
  accessGroups:
  - MarineMain
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: xo
  minimapBackground:
   sprite: _RMC14/Interface/map_blips.rsi
   state: background_command
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillConstruction: 2
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillIntel: 2
        RMCSkillJtac: 4
        RMCSkillLeadership: 3
        RMCSkillMedical: 3
        RMCSkillNavigations: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillVehicles: 1
    - type: MarineOrders
    - type: CMVendorUser
      points: 120
    - type: RMCPointing
    - type: JobPrefix
      prefix: cm-job-prefix-executive-officer
    - type: ViewIntelObjectives
    - type: CommandAccent

- type: startingGear
  id: CMGearExecutiveOfficer
  equipment:
    jumpsuit: CMJumpsuitBO
    shoes: RMCShoesLaceup
    head: CMHeadCap
    id: CMIDCardExecutiveOfficer
    ears: CMHeadsetSeniorCommand
    pocket1: RMCPouchGeneralLarge
    pocket2: RMCPouchGeneralLarge

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointExecutiveOfficer
  name: executive officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMExecutiveOfficer
  - type: Sprite
    state: xo_spawn

- type: playTimeTracker
  id: CMJobExecutiveOfficer
  isHumanoid: true
