- type: job
  parent: CMSurvivor
  id: CMSurvivorCorporate
  name: cm-job-name-survivor-corporate
  description: cm-job-description-survivor
  setPreference: false
  playTimeTracker: CMJobSurvivorCorporate
  ranks:
    RMCRankWeYaExecutiveSpecialist:
    - !type:RoleTimeRequirement
      role: CMJobLiaison
      time: 630000 # 175 hours
    RMCRankWeYaSeniorExecutive:
    - !type:RoleTimeRequirement
      role: CMJobLiaison
      time: 252000 # 70 hours
    RMCRankWeYaExecutive:
    - !type:RoleTimeRequirement
      role: CMJobLiaison
      time: 90000 # 25 hours
    RMCRankWeYaJuniorExecutive: []
  startingGear: RMCGearSurvivorCorporate
  accessGroups:
  - ColonistCorporate
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillEndurance: 2
        RMCSkillFireman: 1
        RMCSkillFirearms: 1
    - type: RMCSurvivor
    - type: RMCRibbon
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - WeYa
      - Survivor
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage

- type: startingGear
  id: RMCGearSurvivorCorporate
  equipment:
    jumpsuit: CMJumpsuitColonist
    shoes: RMCShoesBlack
    id: CMIDCardColonist
    ears: CMHeadsetColony

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorCorporate
  name: survivor corporate spawn point
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite # TODO: Replace with landmark sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - sprite: _RMC14/Markers/cm_jobs.rsi
      state: survivor

- type: playTimeTracker
  id: CMJobSurvivorCorporate
  isHumanoid: true

- type: entity
  parent: RMCSurvivorPresetCivilian
  id: RMCSurvivorPresetCorporate
  name: corporate colonist preset # TODO RMC14 random research notes

- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidSurvivorCorporate
  name: corporate colonist ghost role
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCSurvivorCorporate

- type: randomHumanoidSettings
  parent: RMCSettingsGhostRole
  id: RMCSurvivorCorporate
  components:
  - type: RMCJobSpawner
    job: CMSurvivorCorporate
