- type: job
  parent: CMJobBase
  id: AU14JobGOVFORPlatCo
  name: au14-job-name-govforplatco
  description: au14-job-description-govforplatco
  setPreference: true
  playTimeTracker: AU14JobGOVFORPlatCo
  ranks:
    RMCRankCaptain:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatCo
      time: 7200 # 120 hours
    RMCRankFirstLT: []
  startingGear: AU14GearGOVFORPlatCo
  dummyStartingGear: AU14GearGOVFORPlatCoDummy
  icon: "AU14JobIconPlatCo"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govforplatco
  accessGroups:
  - Rifleman
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillConstruction: 2
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillIntel: 2
        RMCSkillJtac: 4
        RMCSkillLeadership: 3
        RMCSkillMedical: 3
        RMCSkillNavigations: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillVehicles: 1
    - type: JobPrefix
      prefix: au14-job-prefix-govforplatco
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearGOVFORPlatCo
  equipment:
    id: AU14IDCardGOVFORPlatCo

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORPlatCo
  name: Spawn Point GOVFOR Platoon Commander
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORPlatCo
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobGOVFORPlatCo
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORPlatCoDummy
  equipment:
    shoes: CMBootsBlack
    head: CMHeadCapPeakedFormal
    jumpsuit: CMJumpsuitXOFormal