- type: job
  parent: CMJobBase
  id: AU14JobGOVFORPlatOp
  name: au14-job-name-govforplatop
  description: au14-job-description-govforplatop
  setPreference: true
  playTimeTracker: AU14JobGOVFORPlatOp
  ranks:
    RMCRankSecondLT: []
  startingGear: AU14GearGOVFORPlatOp
  dummyStartingGear: AU14GearGOVFORPlatOpDummy
  icon: "AU14JobIconOpsOfc"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - Rifleman
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillConstruction: 2
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillIntel: 2
        RMCSkillJtac: 4
        RMCSkillLeadership: 3
        RMCSkillMedical: 3
        RMCSkillNavigations: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillVehicles: 1
    - type: JobPrefix
      prefix: au14-job-prefix-govforplatop
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearGOVFORPlatOp
  equipment:
    id: AU14IDCardGOVFORPlatOp

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORPlatOp
  name: Spawn Point GOVFOR Platoon Operations Officer
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORPlatOp
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobGOVFORPlatOp
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORPlatOpDummy
  equipment:
    shoes: CMBootsBlack
    head: AU14JunglePatrolCap
    jumpsuit: CMJumpsuitXOFormal